# Scilab ( http://www.scilab.org/ ) - This file is part of Scilab
# Copyright (C) Dassault Systemes - 2022-2023 - Clement DAVID
# Copyright (C) Dassault Systemes - 2022-2023 - Cedric DELAMARRE
#
#
# This YAML file describe the creation/destruction of Docker image.
# This stage is used to set them ready to build.
#

# Create/refresh Docker build
create_docker_image_linux:
  stage: docker_create
  image: docker:20.10.16
  tags: [x86_64-linux-gnu, docker, scilab]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - .gitlab-ci/docker_setup.sh --builder $DOCKER_LINUX_BUILDER $DOCKER_TAG
    - docker logout $CI_REGISTRY
  rules:
    - if: $CI_PROJECT_PATH_SLUG !~ /scilab-scilab/
      changes: &DOCKER_CHANGES
        paths:
          - .gitlab-ci.yml
          - .gitlab-ci/docker_setup.yml
          - .gitlab-ci/docker_setup.sh
          - .gitlab-ci/Dockerfile*
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: *DOCKER_CHANGES
      allow_failure: true
    - if: $CI_MERGE_REQUEST_APPROVED
      changes: *DOCKER_CHANGES
      allow_failure: true

create_docker_image_linux_tests:
  stage: docker_create
  image: docker:20.10.16
  tags: [x86_64-linux-gnu, docker, scilab]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - .gitlab-ci/docker_setup.sh --registry $CI_REGISTRY_IMAGE $DOCKER_TAG
    - docker logout $CI_REGISTRY
  rules:
    - if: $CI_PROJECT_PATH_SLUG !~ /scilab-scilab/
      changes: &DOCKER_CHANGES
        paths:
          - .gitlab-ci.yml
          - .gitlab-ci/docker_setup.yml
          - .gitlab-ci/docker_setup.sh
          - .gitlab-ci/linux-images/Dockerfile*
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: *DOCKER_CHANGES
      allow_failure: true
    - if: $CI_MERGE_REQUEST_APPROVED
      changes: *DOCKER_CHANGES
      allow_failure: true

# create_docker_image_windows:
#   stage: docker_create
#   tags: [x64_windows, shell, scilab]
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker build --memory 4GB --file .gitlab-ci/Dockerfile.windows -t $DOCKER_WINDOWS_BUILDER .
#     - docker push $DOCKER_WINDOWS_BUILDER
#     - docker logout $CI_REGISTRY
#   rules:
#     - changes: *DOCKER_CHANGES